apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: {{ .Values.mysql.PORT | default 3306 }}
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicas | default 1 }}
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type:  {{ .Values.mysql.strategy_type }}
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: {{ .Values.mysql.image }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: {{ .Values.mysql.PASSWORD}}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.DATABASE }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.USER }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: {{ .Values.mysql.PASSWORD }}
        ports:
        - containerPort: {{ .Values.mysql.PORT | default 3306 }}
          name: mysql
        volumeMounts:
        - name: mysql-ps
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc