apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: {{ .Values.mesql.storage_capacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.mesql.host_storage_path }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mesql.storage_capacity }}
  selector:
    matchLabels:
      app: mysql