apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: {{ .Values.wordpress.replicas}}
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: {{ .Values.wordpress.strategy_type }}
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: {{ .Values.wordpress.image }}
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: {{ .Values.mysql.PASSWORD }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.USER }}
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-ps
          mountPath: /var/www/html
      volumes:
      - name: wordpress-ps
        persistentVolumeClaim:
          claimName: wordpress-pvc